export const categories = [
  { label: 'Quick', value: 'quick' },
  { label: 'Easy', value: 'easy' },
  { label: 'Healthy', value: 'healthy' },
  { label: 'Vegetarian', value: 'vegetarian' },
  { label: 'Vegan', value: 'vegan' },
  { label: 'Gluten-Free', value: 'gluten-free' },
  { label: 'Dairy-Free', value: 'dairy-free' },
  { label: 'Low-Carb', value: 'low-carb' },
  { label: 'High-Protein', value: 'high-protein' },
  { label: 'Kid-Friendly', value: 'kid-friendly' },
  { label: 'Budget-Friendly', value: 'budget-friendly' },
  { label: 'Comfort Food', value: 'comfort-food' },
  { label: 'One-Pot Meals', value: 'one-pot-meals' },
  { label: 'Slow Cooker', value: 'slow-cooker' },
  { label: 'Grilling', value: 'grilling' },
  { label: 'Baking', value: 'baking' },
  { label: 'Raw', value: 'raw' },
  { label: 'Holiday', value: 'holiday' },
  { label: 'Seasonal', value: 'seasonal' },
  { label: 'Spicy', value: 'spicy' },
  { label: 'Low-Fat', value: 'low-fat' },
  { label: 'Low-Sugar', value: 'low-sugar' },
  { label: 'Under 30 Minutes', value: 'under-30-minutes' },
  { label: 'Under 15 Minutes', value: 'under-15-minutes' },
  { label: 'Meal Prep', value: 'meal-prep' },
  { label: 'Freezer-Friendly', value: 'freezer-friendly' },
  { label: 'Paleo', value: 'paleo' },
  { label: 'Keto', value: 'keto' },
  { label: 'Mediterranean', value: 'mediterranean' },
  { label: 'Comfort Food', value: 'comfort-food' },
  { label: 'Gourmet', value: 'gourmet' },
  { label: 'Fusion', value: 'fusion' },
  { label: 'Traditional', value: 'traditional' },
  { label: 'Spiritual', value: 'spiritual' },
  { label: 'Organic', value: 'organic' },
  { label: 'Farm-to-Table', value: 'farm-to-table' },
  { label: 'Sustainable', value: 'sustainable' },
];
