export const cuisineTypes = [
  { label: 'African', value: 'african' },
  { label: 'American', value: 'american' },
  { label: 'Australian', value: 'australian' },
  { label: 'Belgian', value: 'belgian' },
  { label: 'Brazilian', value: 'brazilian' },
  { label: 'British', value: 'british' },
  { label: 'Caribbean', value: 'caribbean' },
  { label: 'Cajun', value: 'cajun' },
  { label: 'Central American', value: 'central-american' },
  { label: 'Chinese', value: 'chinese' },
  { label: 'Cuban', value: 'cuban' },
  { label: 'Eastern European', value: 'eastern-european' },
  { label: 'Ethiopian', value: 'ethiopian' },
  { label: 'Filipino', value: 'filipino' },
  { label: 'French', value: 'french' },
  { label: 'German', value: 'german' },
  { label: 'Greek', value: 'greek' },
  { label: 'Hawaiian', value: 'hawaiian' },
  { label: 'Indian', value: 'indian' },
  { label: 'Indonesian', value: 'indonesian' },
  { label: 'Israeli', value: 'israeli' },
  { label: 'Italian', value: 'italian' },
  { label: 'Japanese', value: 'japanese' },
  { label: 'Jamaican', value: 'jamaican' },
  { label: 'Korean', value: 'korean' },
  { label: 'Lebanese', value: 'lebanese' },
  { label: 'Malaysian', value: 'malaysian' },
  { label: 'Mexican', value: 'mexican' },
  { label: 'Middle Eastern', value: 'middle-eastern' },
  { label: 'Moroccan', value: 'moroccan' },
  { label: 'Pakistani', value: 'pakistani' },
  { label: 'Peruvian', value: 'peruvian' },
  { label: 'Polish', value: 'polish' },
  { label: 'Portuguese', value: 'portuguese' },
  { label: 'Russian', value: 'russian' },
  { label: 'Scandinavian', value: 'scandinavian' },
  { label: 'South African', value: 'south-african' },
  { label: 'Spanish', value: 'spanish' },
  { label: 'Sri Lankan', value: 'sri-lankan' },
  { label: 'Swiss', value: 'swiss' },
  { label: 'Thai', value: 'thai' },
  { label: 'Turkish', value: 'turkish' },
  { label: 'Vietnamese', value: 'vietnamese' },
  { label: 'Other', value: 'other' },
];
