export const mealTypes = [
  { label: 'Breakfast', value: 'breakfast' },
  { label: 'Brunch', value: 'brunch' },
  { label: 'Lunch', value: 'lunch' },
  { label: 'Dinner', value: 'dinner' },
  { label: 'Snack', value: 'snack' },
  { label: 'Dessert', value: 'dessert' },
  { label: 'Appetizer', value: 'appetizer' },
  { label: 'Main Course', value: 'main-course' },
  { label: 'Side Dish', value: 'side-dish' },
  { label: 'Soup', value: 'soup' },
  { label: 'Salad', value: 'salad' },
  { label: 'Beverage', value: 'beverage' },
  { label: 'Cocktail', value: 'cocktail' },
  { label: 'Sauce', value: 'sauce' },
  { label: 'Bread', value: 'bread' },
  { label: 'Condiment', value: 'condiment' },
  { label: 'Marinade', value: 'marinade' },
  { label: 'Finger Food', value: 'finger-food' },
  { label: 'Spread', value: 'spread' },
  { label: 'Dip', value: 'dip' },
];
